# NOTE: This file is auto generated by OpenAPI Generator 7.13.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule WikibaseRESTAPI.Model.AddItemRequestAllOfItemStatementsValueInnerAllOfValue do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :content,
    :type
  ]

  @type t :: %__MODULE__{
    :content => any() | nil,
    :type => String.t | nil
  }

  def decode(value) do
    value
  end
end

