# NOTE: This file is auto generated by OpenAPI Generator 7.13.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule WikibaseRESTAPI.Model.AddItemRequestAllOfItemStatementsValueInnerAllOfProperty do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :id,
    :data_type
  ]

  @type t :: %__MODULE__{
    :id => String.t | nil,
    :data_type => String.t | nil
  }

  def decode(value) do
    value
  end
end

