# NOTE: This file is auto generated by OpenAPI Generator 7.13.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule WikibaseRESTAPI.Model.AddItemStatementRequestAllOfStatement do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :id,
    :rank,
    :property,
    :value,
    :qualifiers,
    :references
  ]

  @type t :: %__MODULE__{
    :id => String.t | nil,
    :rank => String.t | nil,
    :property => any() | nil,
    :value => any() | nil,
    :qualifiers => any() | nil,
    :references => any() | nil
  }

  def decode(value) do
    value
  end
end

