# NOTE: This file is auto generated by OpenAPI Generator 7.13.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule WikibaseRESTAPI.Model.AddItemRequestAllOfItemStatementsValueInnerAllOfReferencesInner do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :hash,
    :parts
  ]

  @type t :: %__MODULE__{
    :hash => String.t | nil,
    :parts => [WikibaseRESTAPI.Model.AddItemRequestAllOfItemStatementsValueInnerAllOfQualifiersInner.t] | nil
  }

  alias WikibaseRESTAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:parts, :list, WikibaseRESTAPI.Model.AddItemRequestAllOfItemStatementsValueInnerAllOfQualifiersInner)
  end
end

