# NOTE: This file is auto generated by OpenAPI Generator 7.13.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule WikibaseRESTAPI.Model.AddProperty201Response do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :id,
    :type,
    :data_type,
    :labels,
    :descriptions,
    :aliases,
    :statements
  ]

  @type t :: %__MODULE__{
    :id => String.t,
    :type => String.t,
    :data_type => String.t,
    :labels => %{optional(String.t) => String.t},
    :descriptions => %{optional(String.t) => String.t},
    :aliases => %{optional(String.t) => [String.t]},
    :statements => %{optional(String.t) => any()} | nil
  }

  def decode(value) do
    value
  end
end

