# NOTE: This file is auto generated by OpenAPI Generator 7.13.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule WikibaseRESTAPI.Model.GetItemStatements200ResponseValueInnerAllOfAllOfReferences do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :parts
  ]

  @type t :: %__MODULE__{
    :parts => any() | nil
  }

  def decode(value) do
    value
  end
end

