# NOTE: This file is auto generated by OpenAPI Generator 7.13.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule WikibaseRESTAPI.Model.PatchItemRequest do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :patch,
    :tags,
    :bot,
    :comment
  ]

  @type t :: %__MODULE__{
    :patch => [WikibaseRESTAPI.Model.PatchItemRequestAllOfPatchInner.t],
    :tags => [String.t] | nil,
    :bot => boolean() | nil,
    :comment => String.t | nil
  }

  alias WikibaseRESTAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:patch, :list, WikibaseRESTAPI.Model.PatchItemRequestAllOfPatchInner)
  end
end

