# NOTE: This file is auto generated by OpenAPI Generator 7.13.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule WikibaseRESTAPI.Model.PatchItemRequestAllOfPatchInner do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :op,
    :path,
    :from,
    :value
  ]

  @type t :: %__MODULE__{
    :op => String.t,
    :path => String.t,
    :from => String.t | nil,
    :value => any() | nil
  }

  def decode(value) do
    value
  end
end

