# NOTE: This file is auto generated by OpenAPI Generator 7.13.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule WikibaseRESTAPI.Model.SearchItem200Response do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :results
  ]

  @type t :: %__MODULE__{
    :results => [WikibaseRESTAPI.Model.SearchItem200ResponseResultsInner.t] | nil
  }

  alias WikibaseRESTAPI.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:results, :list, WikibaseRESTAPI.Model.SearchItem200ResponseResultsInner)
  end
end

