# NOTE: This file is auto generated by OpenAPI Generator 7.13.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule WikibaseRESTAPI.Model.Sitelink do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :title,
    :badges,
    :url
  ]

  @type t :: %__MODULE__{
    :title => String.t,
    :badges => [String.t] | nil,
    :url => String.t | nil
  }

  def decode(value) do
    value
  end
end

