# NOTE: This file is auto generated by OpenAPI Generator 7.13.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule WikibaseRESTAPI.Api.Descriptions do
  @moduledoc """
  API calls for all endpoints tagged `Descriptions`.
  """

  alias WikibaseRESTAPI.Connection
  import WikibaseRESTAPI.RequestBuilder

  @doc """
  Delete an Item's description in a specific language

  ### Parameters

  - `connection` (WikibaseRESTAPI.Connection): Connection to server
  - `item_id` (String.t): The ID of the required Item
  - `language_code` (String.t): The requested resource language
  - `opts` (keyword): Optional parameters
    - `:"If-None-Match"` ([String.t]): Conditionally perform the request only if the resource has been modified since the specified entity revision numbers
    - `:"If-Modified-Since"` (String.t): Conditionally perform the request only if the resource has been modified after the specified date
    - `:"If-Match"` ([String.t]): Conditionally perform the request only if the resource has not been modified since one of the specified entity revision numbers
    - `:"If-Unmodified-Since"` (String.t): Conditionally perform the request only if the resource has not been modified after the specified date
    - `:Authorization` (String.t): Make authenticated request using a provided bearer token
    - `:body` (DeleteSitelinkRequest): Edit payload containing edit metadata

  ### Returns

  - `{:ok, String.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec delete_item_description(Tesla.Env.client, String.t, String.t, keyword()) :: {:ok, WikibaseRESTAPI.Model.AddItem400Response.t} | {:ok, nil} | {:ok, String.t} | {:error, Tesla.Env.t}
  def delete_item_description(connection, item_id, language_code, opts \\ []) do
    optional_params = %{
      :"If-None-Match" => :headers,
      :"If-Modified-Since" => :headers,
      :"If-Match" => :headers,
      :"If-Unmodified-Since" => :headers,
      :Authorization => :headers,
      :body => :body
    }

    request =
      %{}
      |> method(:delete)
      |> url("/v1/entities/items/#{item_id}/descriptions/#{language_code}")
      |> add_optional_params(optional_params, opts)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, false},
      {400, WikibaseRESTAPI.Model.AddItem400Response},
      {403, WikibaseRESTAPI.Model.AddItem400Response},
      {404, WikibaseRESTAPI.Model.AddItem400Response},
      {409, WikibaseRESTAPI.Model.AddItem400Response},
      {412, false},
      {429, WikibaseRESTAPI.Model.AddItem400Response},
      {500, WikibaseRESTAPI.Model.AddItem400Response}
    ])
  end

  @doc """
  Delete a Property's description in a specific language

  ### Parameters

  - `connection` (WikibaseRESTAPI.Connection): Connection to server
  - `property_id` (String.t): The ID of the required Property
  - `language_code` (String.t): The requested resource language
  - `opts` (keyword): Optional parameters
    - `:"If-None-Match"` ([String.t]): Conditionally perform the request only if the resource has been modified since the specified entity revision numbers
    - `:"If-Modified-Since"` (String.t): Conditionally perform the request only if the resource has been modified after the specified date
    - `:"If-Match"` ([String.t]): Conditionally perform the request only if the resource has not been modified since one of the specified entity revision numbers
    - `:"If-Unmodified-Since"` (String.t): Conditionally perform the request only if the resource has not been modified after the specified date
    - `:Authorization` (String.t): Make authenticated request using a provided bearer token
    - `:body` (DeleteSitelinkRequest): Edit payload containing edit metadata

  ### Returns

  - `{:ok, String.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec delete_property_description(Tesla.Env.client, String.t, String.t, keyword()) :: {:ok, WikibaseRESTAPI.Model.AddItem400Response.t} | {:ok, nil} | {:ok, String.t} | {:error, Tesla.Env.t}
  def delete_property_description(connection, property_id, language_code, opts \\ []) do
    optional_params = %{
      :"If-None-Match" => :headers,
      :"If-Modified-Since" => :headers,
      :"If-Match" => :headers,
      :"If-Unmodified-Since" => :headers,
      :Authorization => :headers,
      :body => :body
    }

    request =
      %{}
      |> method(:delete)
      |> url("/v1/entities/properties/#{property_id}/descriptions/#{language_code}")
      |> add_optional_params(optional_params, opts)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, false},
      {400, WikibaseRESTAPI.Model.AddItem400Response},
      {403, WikibaseRESTAPI.Model.AddItem400Response},
      {404, WikibaseRESTAPI.Model.AddItem400Response},
      {412, false},
      {429, WikibaseRESTAPI.Model.AddItem400Response},
      {500, WikibaseRESTAPI.Model.AddItem400Response}
    ])
  end

  @doc """
  Retrieve an Item's description in a specific language

  ### Parameters

  - `connection` (WikibaseRESTAPI.Connection): Connection to server
  - `item_id` (String.t): The ID of the required Item
  - `language_code` (String.t): The requested resource language
  - `opts` (keyword): Optional parameters
    - `:"If-None-Match"` ([String.t]): Conditionally perform the request only if the resource has been modified since the specified entity revision numbers
    - `:"If-Modified-Since"` (String.t): Conditionally perform the request only if the resource has been modified after the specified date
    - `:"If-Match"` ([String.t]): Conditionally perform the request only if the resource has not been modified since one of the specified entity revision numbers
    - `:"If-Unmodified-Since"` (String.t): Conditionally perform the request only if the resource has not been modified after the specified date
    - `:Authorization` (String.t): Make authenticated request using a provided bearer token

  ### Returns

  - `{:ok, String.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec get_item_description(Tesla.Env.client, String.t, String.t, keyword()) :: {:ok, nil} | {:ok, WikibaseRESTAPI.Model.AddItem400Response.t} | {:ok, String.t} | {:error, Tesla.Env.t}
  def get_item_description(connection, item_id, language_code, opts \\ []) do
    optional_params = %{
      :"If-None-Match" => :headers,
      :"If-Modified-Since" => :headers,
      :"If-Match" => :headers,
      :"If-Unmodified-Since" => :headers,
      :Authorization => :headers
    }

    request =
      %{}
      |> method(:get)
      |> url("/v1/entities/items/#{item_id}/descriptions/#{language_code}")
      |> add_optional_params(optional_params, opts)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, false},
      {304, false},
      {308, false},
      {400, WikibaseRESTAPI.Model.AddItem400Response},
      {404, WikibaseRESTAPI.Model.AddItem400Response},
      {412, false},
      {500, WikibaseRESTAPI.Model.AddItem400Response}
    ])
  end

  @doc """
  Retrieve an Item's description in a specific language, with language fallback. If a description is defined in the requested language, the API responds with a 200 status code and includes the description in the response payload. If a description only exists in a fallback language, the API returns a 307 status code and provides the location of the description

  ### Parameters

  - `connection` (WikibaseRESTAPI.Connection): Connection to server
  - `item_id` (String.t): The ID of the required Item
  - `language_code` (String.t): The requested resource language
  - `opts` (keyword): Optional parameters
    - `:"If-None-Match"` ([String.t]): Conditionally perform the request only if the resource has been modified since the specified entity revision numbers
    - `:"If-Modified-Since"` (String.t): Conditionally perform the request only if the resource has been modified after the specified date
    - `:"If-Match"` ([String.t]): Conditionally perform the request only if the resource has not been modified since one of the specified entity revision numbers
    - `:"If-Unmodified-Since"` (String.t): Conditionally perform the request only if the resource has not been modified after the specified date
    - `:Authorization` (String.t): Make authenticated request using a provided bearer token

  ### Returns

  - `{:ok, String.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec get_item_description_with_fallback(Tesla.Env.client, String.t, String.t, keyword()) :: {:ok, nil} | {:ok, WikibaseRESTAPI.Model.AddItem400Response.t} | {:ok, String.t} | {:error, Tesla.Env.t}
  def get_item_description_with_fallback(connection, item_id, language_code, opts \\ []) do
    optional_params = %{
      :"If-None-Match" => :headers,
      :"If-Modified-Since" => :headers,
      :"If-Match" => :headers,
      :"If-Unmodified-Since" => :headers,
      :Authorization => :headers
    }

    request =
      %{}
      |> method(:get)
      |> url("/v1/entities/items/#{item_id}/descriptions_with_language_fallback/#{language_code}")
      |> add_optional_params(optional_params, opts)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, false},
      {304, false},
      {307, false},
      {308, false},
      {400, WikibaseRESTAPI.Model.AddItem400Response},
      {404, WikibaseRESTAPI.Model.AddItem400Response},
      {412, false},
      {500, WikibaseRESTAPI.Model.AddItem400Response}
    ])
  end

  @doc """
  Retrieve an Item's descriptions

  ### Parameters

  - `connection` (WikibaseRESTAPI.Connection): Connection to server
  - `item_id` (String.t): The ID of the required Item
  - `opts` (keyword): Optional parameters
    - `:"If-None-Match"` ([String.t]): Conditionally perform the request only if the resource has been modified since the specified entity revision numbers
    - `:"If-Modified-Since"` (String.t): Conditionally perform the request only if the resource has been modified after the specified date
    - `:"If-Match"` ([String.t]): Conditionally perform the request only if the resource has not been modified since one of the specified entity revision numbers
    - `:"If-Unmodified-Since"` (String.t): Conditionally perform the request only if the resource has not been modified after the specified date
    - `:Authorization` (String.t): Make authenticated request using a provided bearer token

  ### Returns

  - `{:ok, %{}}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec get_item_descriptions(Tesla.Env.client, String.t, keyword()) :: {:ok, map()} | {:ok, nil} | {:ok, WikibaseRESTAPI.Model.AddItem400Response.t} | {:error, Tesla.Env.t}
  def get_item_descriptions(connection, item_id, opts \\ []) do
    optional_params = %{
      :"If-None-Match" => :headers,
      :"If-Modified-Since" => :headers,
      :"If-Match" => :headers,
      :"If-Unmodified-Since" => :headers,
      :Authorization => :headers
    }

    request =
      %{}
      |> method(:get)
      |> url("/v1/entities/items/#{item_id}/descriptions")
      |> add_optional_params(optional_params, opts)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, %{}},
      {304, false},
      {308, false},
      {400, WikibaseRESTAPI.Model.AddItem400Response},
      {404, WikibaseRESTAPI.Model.AddItem400Response},
      {412, false},
      {500, WikibaseRESTAPI.Model.AddItem400Response}
    ])
  end

  @doc """
  Retrieve a Property's description in a specific language

  ### Parameters

  - `connection` (WikibaseRESTAPI.Connection): Connection to server
  - `property_id` (String.t): The ID of the required Property
  - `language_code` (String.t): The requested resource language
  - `opts` (keyword): Optional parameters
    - `:"If-None-Match"` ([String.t]): Conditionally perform the request only if the resource has been modified since the specified entity revision numbers
    - `:"If-Modified-Since"` (String.t): Conditionally perform the request only if the resource has been modified after the specified date
    - `:"If-Match"` ([String.t]): Conditionally perform the request only if the resource has not been modified since one of the specified entity revision numbers
    - `:"If-Unmodified-Since"` (String.t): Conditionally perform the request only if the resource has not been modified after the specified date
    - `:Authorization` (String.t): Make authenticated request using a provided bearer token

  ### Returns

  - `{:ok, String.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec get_property_description(Tesla.Env.client, String.t, String.t, keyword()) :: {:ok, nil} | {:ok, WikibaseRESTAPI.Model.AddItem400Response.t} | {:ok, String.t} | {:error, Tesla.Env.t}
  def get_property_description(connection, property_id, language_code, opts \\ []) do
    optional_params = %{
      :"If-None-Match" => :headers,
      :"If-Modified-Since" => :headers,
      :"If-Match" => :headers,
      :"If-Unmodified-Since" => :headers,
      :Authorization => :headers
    }

    request =
      %{}
      |> method(:get)
      |> url("/v1/entities/properties/#{property_id}/descriptions/#{language_code}")
      |> add_optional_params(optional_params, opts)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, false},
      {304, false},
      {400, WikibaseRESTAPI.Model.AddItem400Response},
      {404, WikibaseRESTAPI.Model.AddItem400Response},
      {412, false},
      {500, WikibaseRESTAPI.Model.AddItem400Response}
    ])
  end

  @doc """
  Retrieve a Property's description in a specific language, with language fallback. If a description is defined in the requested language, the API responds with a 200 status code and includes the description in the response payload. If a description only exists in a fallback language, the API returns a 307 status code and provides the location of the description

  ### Parameters

  - `connection` (WikibaseRESTAPI.Connection): Connection to server
  - `property_id` (String.t): The ID of the required Property
  - `language_code` (String.t): The requested resource language
  - `opts` (keyword): Optional parameters
    - `:"If-None-Match"` ([String.t]): Conditionally perform the request only if the resource has been modified since the specified entity revision numbers
    - `:"If-Modified-Since"` (String.t): Conditionally perform the request only if the resource has been modified after the specified date
    - `:"If-Match"` ([String.t]): Conditionally perform the request only if the resource has not been modified since one of the specified entity revision numbers
    - `:"If-Unmodified-Since"` (String.t): Conditionally perform the request only if the resource has not been modified after the specified date
    - `:Authorization` (String.t): Make authenticated request using a provided bearer token

  ### Returns

  - `{:ok, String.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec get_property_description_with_fallback(Tesla.Env.client, String.t, String.t, keyword()) :: {:ok, nil} | {:ok, WikibaseRESTAPI.Model.AddItem400Response.t} | {:ok, String.t} | {:error, Tesla.Env.t}
  def get_property_description_with_fallback(connection, property_id, language_code, opts \\ []) do
    optional_params = %{
      :"If-None-Match" => :headers,
      :"If-Modified-Since" => :headers,
      :"If-Match" => :headers,
      :"If-Unmodified-Since" => :headers,
      :Authorization => :headers
    }

    request =
      %{}
      |> method(:get)
      |> url("/v1/entities/properties/#{property_id}/descriptions_with_language_fallback/#{language_code}")
      |> add_optional_params(optional_params, opts)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, false},
      {304, false},
      {307, false},
      {400, WikibaseRESTAPI.Model.AddItem400Response},
      {404, WikibaseRESTAPI.Model.AddItem400Response},
      {412, false},
      {500, WikibaseRESTAPI.Model.AddItem400Response}
    ])
  end

  @doc """
  Retrieve a Property's descriptions

  ### Parameters

  - `connection` (WikibaseRESTAPI.Connection): Connection to server
  - `property_id` (String.t): The ID of the required Property
  - `opts` (keyword): Optional parameters
    - `:"If-None-Match"` ([String.t]): Conditionally perform the request only if the resource has been modified since the specified entity revision numbers
    - `:"If-Modified-Since"` (String.t): Conditionally perform the request only if the resource has been modified after the specified date
    - `:"If-Match"` ([String.t]): Conditionally perform the request only if the resource has not been modified since one of the specified entity revision numbers
    - `:"If-Unmodified-Since"` (String.t): Conditionally perform the request only if the resource has not been modified after the specified date
    - `:Authorization` (String.t): Make authenticated request using a provided bearer token

  ### Returns

  - `{:ok, %{}}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec get_property_descriptions(Tesla.Env.client, String.t, keyword()) :: {:ok, map()} | {:ok, nil} | {:ok, WikibaseRESTAPI.Model.AddItem400Response.t} | {:error, Tesla.Env.t}
  def get_property_descriptions(connection, property_id, opts \\ []) do
    optional_params = %{
      :"If-None-Match" => :headers,
      :"If-Modified-Since" => :headers,
      :"If-Match" => :headers,
      :"If-Unmodified-Since" => :headers,
      :Authorization => :headers
    }

    request =
      %{}
      |> method(:get)
      |> url("/v1/entities/properties/#{property_id}/descriptions")
      |> add_optional_params(optional_params, opts)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, %{}},
      {304, false},
      {400, WikibaseRESTAPI.Model.AddItem400Response},
      {404, WikibaseRESTAPI.Model.AddItem400Response},
      {412, false},
      {500, WikibaseRESTAPI.Model.AddItem400Response}
    ])
  end

  @doc """
  Change an Item's descriptions

  ### Parameters

  - `connection` (WikibaseRESTAPI.Connection): Connection to server
  - `item_id` (String.t): The ID of the required Item
  - `patch_item_request` (PatchItemRequest): Payload containing a JSON Patch document to be applied to an Item's descriptions and edit metadata
  - `opts` (keyword): Optional parameters
    - `:"If-Match"` ([String.t]): Conditionally perform the request only if the resource has not been modified since one of the specified entity revision numbers
    - `:"If-None-Match"` ([String.t]): Conditionally perform the request only if the resource has been modified since the specified entity revision numbers
    - `:"If-Unmodified-Since"` (String.t): Conditionally perform the request only if the resource has not been modified after the specified date

  ### Returns

  - `{:ok, %{}}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec patch_item_descriptions(Tesla.Env.client, String.t, WikibaseRESTAPI.Model.PatchItemRequest.t, keyword()) :: {:ok, map()} | {:ok, WikibaseRESTAPI.Model.AddItem400Response.t} | {:ok, nil} | {:error, Tesla.Env.t}
  def patch_item_descriptions(connection, item_id, patch_item_request, opts \\ []) do
    optional_params = %{
      :"If-Match" => :headers,
      :"If-None-Match" => :headers,
      :"If-Unmodified-Since" => :headers
    }

    request =
      %{}
      |> method(:patch)
      |> url("/v1/entities/items/#{item_id}/descriptions")
      |> add_param(:body, :body, patch_item_request)
      |> add_optional_params(optional_params, opts)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, %{}},
      {400, WikibaseRESTAPI.Model.AddItem400Response},
      {403, WikibaseRESTAPI.Model.AddItem400Response},
      {404, WikibaseRESTAPI.Model.AddItem400Response},
      {409, WikibaseRESTAPI.Model.AddItem400Response},
      {412, false},
      {422, WikibaseRESTAPI.Model.AddItem400Response},
      {429, WikibaseRESTAPI.Model.AddItem400Response},
      {500, WikibaseRESTAPI.Model.AddItem400Response}
    ])
  end

  @doc """
  Change a Property's descriptions

  ### Parameters

  - `connection` (WikibaseRESTAPI.Connection): Connection to server
  - `property_id` (String.t): The ID of the required Property
  - `patch_item_request` (PatchItemRequest): Payload containing a JSON Patch document to be applied to a Property's descriptions and edit metadata
  - `opts` (keyword): Optional parameters
    - `:"If-Match"` ([String.t]): Conditionally perform the request only if the resource has not been modified since one of the specified entity revision numbers
    - `:"If-None-Match"` ([String.t]): Conditionally perform the request only if the resource has been modified since the specified entity revision numbers
    - `:"If-Unmodified-Since"` (String.t): Conditionally perform the request only if the resource has not been modified after the specified date

  ### Returns

  - `{:ok, %{}}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec patch_property_descriptions(Tesla.Env.client, String.t, WikibaseRESTAPI.Model.PatchItemRequest.t, keyword()) :: {:ok, map()} | {:ok, WikibaseRESTAPI.Model.AddItem400Response.t} | {:ok, nil} | {:error, Tesla.Env.t}
  def patch_property_descriptions(connection, property_id, patch_item_request, opts \\ []) do
    optional_params = %{
      :"If-Match" => :headers,
      :"If-None-Match" => :headers,
      :"If-Unmodified-Since" => :headers
    }

    request =
      %{}
      |> method(:patch)
      |> url("/v1/entities/properties/#{property_id}/descriptions")
      |> add_param(:body, :body, patch_item_request)
      |> add_optional_params(optional_params, opts)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, %{}},
      {400, WikibaseRESTAPI.Model.AddItem400Response},
      {403, WikibaseRESTAPI.Model.AddItem400Response},
      {404, WikibaseRESTAPI.Model.AddItem400Response},
      {409, WikibaseRESTAPI.Model.AddItem400Response},
      {412, false},
      {422, WikibaseRESTAPI.Model.AddItem400Response},
      {429, WikibaseRESTAPI.Model.AddItem400Response},
      {500, WikibaseRESTAPI.Model.AddItem400Response}
    ])
  end

  @doc """
  Add / Replace an Item's description in a specific language

  ### Parameters

  - `connection` (WikibaseRESTAPI.Connection): Connection to server
  - `item_id` (String.t): The ID of the required Item
  - `language_code` (String.t): The requested resource language
  - `replace_item_description_request` (ReplaceItemDescriptionRequest): Payload containing Item description in the specified language and edit metadata
  - `opts` (keyword): Optional parameters
    - `:"If-None-Match"` ([String.t]): Conditionally perform the request only if the resource has been modified since the specified entity revision numbers
    - `:"If-Modified-Since"` (String.t): Conditionally perform the request only if the resource has been modified after the specified date
    - `:"If-Match"` ([String.t]): Conditionally perform the request only if the resource has not been modified since one of the specified entity revision numbers
    - `:"If-Unmodified-Since"` (String.t): Conditionally perform the request only if the resource has not been modified after the specified date
    - `:Authorization` (String.t): Make authenticated request using a provided bearer token

  ### Returns

  - `{:ok, String.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec replace_item_description(Tesla.Env.client, String.t, String.t, WikibaseRESTAPI.Model.ReplaceItemDescriptionRequest.t, keyword()) :: {:ok, nil} | {:ok, WikibaseRESTAPI.Model.AddItem400Response.t} | {:ok, String.t} | {:error, Tesla.Env.t}
  def replace_item_description(connection, item_id, language_code, replace_item_description_request, opts \\ []) do
    optional_params = %{
      :"If-None-Match" => :headers,
      :"If-Modified-Since" => :headers,
      :"If-Match" => :headers,
      :"If-Unmodified-Since" => :headers,
      :Authorization => :headers
    }

    request =
      %{}
      |> method(:put)
      |> url("/v1/entities/items/#{item_id}/descriptions/#{language_code}")
      |> add_param(:body, :body, replace_item_description_request)
      |> add_optional_params(optional_params, opts)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, false},
      {201, false},
      {304, false},
      {400, WikibaseRESTAPI.Model.AddItem400Response},
      {403, WikibaseRESTAPI.Model.AddItem400Response},
      {404, WikibaseRESTAPI.Model.AddItem400Response},
      {409, WikibaseRESTAPI.Model.AddItem400Response},
      {412, false},
      {422, WikibaseRESTAPI.Model.AddItem400Response},
      {429, WikibaseRESTAPI.Model.AddItem400Response},
      {500, WikibaseRESTAPI.Model.AddItem400Response}
    ])
  end

  @doc """
  Add / Replace a Property's description in a specific language

  ### Parameters

  - `connection` (WikibaseRESTAPI.Connection): Connection to server
  - `property_id` (String.t): The ID of the required Property
  - `language_code` (String.t): The requested resource language
  - `opts` (keyword): Optional parameters
    - `:"If-None-Match"` ([String.t]): Conditionally perform the request only if the resource has been modified since the specified entity revision numbers
    - `:"If-Modified-Since"` (String.t): Conditionally perform the request only if the resource has been modified after the specified date
    - `:"If-Match"` ([String.t]): Conditionally perform the request only if the resource has not been modified since one of the specified entity revision numbers
    - `:"If-Unmodified-Since"` (String.t): Conditionally perform the request only if the resource has not been modified after the specified date
    - `:Authorization` (String.t): Make authenticated request using a provided bearer token
    - `:body` (ReplaceItemDescriptionRequest): Payload containing Property description in the specified language and edit metadata

  ### Returns

  - `{:ok, String.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec set_property_description(Tesla.Env.client, String.t, String.t, keyword()) :: {:ok, nil} | {:ok, WikibaseRESTAPI.Model.AddItem400Response.t} | {:ok, String.t} | {:error, Tesla.Env.t}
  def set_property_description(connection, property_id, language_code, opts \\ []) do
    optional_params = %{
      :"If-None-Match" => :headers,
      :"If-Modified-Since" => :headers,
      :"If-Match" => :headers,
      :"If-Unmodified-Since" => :headers,
      :Authorization => :headers,
      :body => :body
    }

    request =
      %{}
      |> method(:put)
      |> url("/v1/entities/properties/#{property_id}/descriptions/#{language_code}")
      |> add_optional_params(optional_params, opts)
      |> ensure_body()
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, false},
      {201, false},
      {304, false},
      {400, WikibaseRESTAPI.Model.AddItem400Response},
      {403, WikibaseRESTAPI.Model.AddItem400Response},
      {404, WikibaseRESTAPI.Model.AddItem400Response},
      {412, false},
      {422, WikibaseRESTAPI.Model.AddItem400Response},
      {429, WikibaseRESTAPI.Model.AddItem400Response},
      {500, WikibaseRESTAPI.Model.AddItem400Response}
    ])
  end
end
