# NOTE: This file is auto generated by OpenAPI Generator 7.13.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule WikibaseRESTAPI.Api.OpenAPIDocument do
  @moduledoc """
  API calls for all endpoints tagged `OpenAPIDocument`.
  """

  alias WikibaseRESTAPI.Connection
  import WikibaseRESTAPI.RequestBuilder

  @doc """
  Retrieve the OpenAPI document

  ### Parameters

  - `connection` (WikibaseRESTAPI.Connection): Connection to server
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, map()}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec get_open_api_doc(Tesla.Env.client, keyword()) :: {:ok, map()} | {:error, Tesla.Env.t}
  def get_open_api_doc(connection, _opts \\ []) do
    request =
      %{}
      |> method(:get)
      |> url("/v1/openapi.json")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, %{}}
    ])
  end
end
