# NOTE: This file is auto generated by OpenAPI Generator 7.13.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule WikibaseRESTAPI.Api.Properties do
  @moduledoc """
  API calls for all endpoints tagged `Properties`.
  """

  alias WikibaseRESTAPI.Connection
  import WikibaseRESTAPI.RequestBuilder

  @doc """
  Create a Wikibase Property

  ### Parameters

  - `connection` (WikibaseRESTAPI.Connection): Connection to server
  - `add_property_request` (AddPropertyRequest): Payload containing a Wikibase Property and edit metadata
  - `opts` (keyword): Optional parameters
    - `:Authorization` (String.t): Make authenticated request using a provided bearer token

  ### Returns

  - `{:ok, WikibaseRESTAPI.Model.AddProperty201Response.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec add_property(Tesla.Env.client, WikibaseRESTAPI.Model.AddPropertyRequest.t, keyword()) :: {:ok, WikibaseRESTAPI.Model.AddItem400Response.t} | {:ok, WikibaseRESTAPI.Model.AddProperty201Response.t} | {:error, Tesla.Env.t}
  def add_property(connection, add_property_request, opts \\ []) do
    optional_params = %{
      :Authorization => :headers
    }

    request =
      %{}
      |> method(:post)
      |> url("/v1/entities/properties")
      |> add_param(:body, :body, add_property_request)
      |> add_optional_params(optional_params, opts)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {201, WikibaseRESTAPI.Model.AddProperty201Response},
      {400, WikibaseRESTAPI.Model.AddItem400Response},
      {403, WikibaseRESTAPI.Model.AddItem400Response},
      {422, WikibaseRESTAPI.Model.AddItem400Response},
      {429, WikibaseRESTAPI.Model.AddItem400Response},
      {500, WikibaseRESTAPI.Model.AddItem400Response}
    ])
  end

  @doc """
  Retrieve a single Wikibase Property by ID

  ### Parameters

  - `connection` (WikibaseRESTAPI.Connection): Connection to server
  - `property_id` (String.t): The ID of the required Property
  - `opts` (keyword): Optional parameters
    - `:_fields` ([String.t]): Comma-separated list of fields to include in each response object.
    - `:"If-None-Match"` ([String.t]): Conditionally perform the request only if the resource has been modified since the specified entity revision numbers
    - `:"If-Modified-Since"` (String.t): Conditionally perform the request only if the resource has been modified after the specified date
    - `:"If-Match"` ([String.t]): Conditionally perform the request only if the resource has not been modified since one of the specified entity revision numbers
    - `:"If-Unmodified-Since"` (String.t): Conditionally perform the request only if the resource has not been modified after the specified date
    - `:Authorization` (String.t): Make authenticated request using a provided bearer token

  ### Returns

  - `{:ok, WikibaseRESTAPI.Model.AddProperty201Response.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec get_property(Tesla.Env.client, String.t, keyword()) :: {:ok, WikibaseRESTAPI.Model.AddItem400Response.t} | {:ok, WikibaseRESTAPI.Model.AddProperty201Response.t} | {:error, Tesla.Env.t}
  def get_property(connection, property_id, opts \\ []) do
    optional_params = %{
      :_fields => :query,
      :"If-None-Match" => :headers,
      :"If-Modified-Since" => :headers,
      :"If-Match" => :headers,
      :"If-Unmodified-Since" => :headers,
      :Authorization => :headers
    }

    request =
      %{}
      |> method(:get)
      |> url("/v1/entities/properties/#{property_id}")
      |> add_optional_params(optional_params, opts)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, WikibaseRESTAPI.Model.AddProperty201Response},
      {400, WikibaseRESTAPI.Model.AddItem400Response},
      {404, WikibaseRESTAPI.Model.AddItem400Response},
      {500, WikibaseRESTAPI.Model.AddItem400Response}
    ])
  end

  @doc """
  Change a single Wikibase Property by ID

  ### Parameters

  - `connection` (WikibaseRESTAPI.Connection): Connection to server
  - `property_id` (String.t): The ID of the required Property
  - `patch_item_request` (PatchItemRequest): 
  - `opts` (keyword): Optional parameters
    - `:"If-Match"` ([String.t]): Conditionally perform the request only if the resource has not been modified since one of the specified entity revision numbers
    - `:"If-None-Match"` ([String.t]): Conditionally perform the request only if the resource has been modified since the specified entity revision numbers
    - `:"If-Unmodified-Since"` (String.t): Conditionally perform the request only if the resource has not been modified after the specified date

  ### Returns

  - `{:ok, WikibaseRESTAPI.Model.AddProperty201Response.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec patch_property(Tesla.Env.client, String.t, WikibaseRESTAPI.Model.PatchItemRequest.t, keyword()) :: {:ok, WikibaseRESTAPI.Model.AddItem400Response.t} | {:ok, nil} | {:ok, WikibaseRESTAPI.Model.AddProperty201Response.t} | {:error, Tesla.Env.t}
  def patch_property(connection, property_id, patch_item_request, opts \\ []) do
    optional_params = %{
      :"If-Match" => :headers,
      :"If-None-Match" => :headers,
      :"If-Unmodified-Since" => :headers
    }

    request =
      %{}
      |> method(:patch)
      |> url("/v1/entities/properties/#{property_id}")
      |> add_param(:body, :body, patch_item_request)
      |> add_optional_params(optional_params, opts)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, WikibaseRESTAPI.Model.AddProperty201Response},
      {400, WikibaseRESTAPI.Model.AddItem400Response},
      {403, WikibaseRESTAPI.Model.AddItem400Response},
      {404, WikibaseRESTAPI.Model.AddItem400Response},
      {409, WikibaseRESTAPI.Model.AddItem400Response},
      {412, false},
      {422, WikibaseRESTAPI.Model.AddItem400Response},
      {429, WikibaseRESTAPI.Model.AddItem400Response},
      {500, WikibaseRESTAPI.Model.AddItem400Response}
    ])
  end
end
